file_path : ./data/example_data/bank-additional-full.csv
images_output_path: ./data/images
powerpoint_output_path: ./data/powerpoints/test.pptx

features:
  - name: euribor3m
  - name: marital
    type: categorical
  - name: education
    type: categorical

target: y1
#target: D_STROOPWAFFELS_AVG_6M_N 


primary_color: 40, 186, 116
secondary_color: 41, 94, 126
tertiary_color: 153, 204, 235
grey_tint_color: 110, 111, 115

#primary_color: 231, 30, 87
#secondary_color: 153, 204, 235
#tertiary_color: 254, 189, 64
#grey_tint_color: 110, 111, 115