file_path : ./data/example_data/test_sample.csv
images_output_path: ./data/images
powerpoint_output_path: ./data/powerpoints/test.pptx


# for each feature, you must specify at least the name.
features:
  - name: A_TENURE_MONTHS_N
  - name: T_PPG_AVG_6M_N
    n_bins: 4
  - name: D_MAX_DAYS_PAST_DUE_6M_N
    bins:
          - 0
          - 1
          - 5
          - 10
          - 100
  - name: LN_LEXISNEXIS_SBFE_SCORE_CURRENT_N
  - name: T_TOTAL_TRX_NON_FUEL_PROPORTION_1M_N
    distplot_q_min: 0.01
    distplot_q_max: 0.99
  - name: LN_LEXISNEXIS_THIN_FILE_FLAG_B
    type: categorical
    #type: float
  #- name: D_STROOPWAFFELS_AVG_6M_N

target: FLAG_60_DPD_366_DAYS
#target: D_STROOPWAFFELS_AVG_6M_N

#primary_color: 40, 186, 116
#secondary_color: 41, 94, 126
#tertiary_color: 153, 204, 235
#grey_tint_color: 110, 111, 115

primary_color: 231, 30, 87
secondary_color: 153, 204, 235
tertiary_color: 254, 189, 64
grey_tint_color: 110, 111, 115
