name: Upload to PyPI

on:
  push:
    branches:
      - main

jobs:
  upload_to_pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Bump version
        run: |
          poetry version patch 

      - name: Build package
        run: poetry build

      - name: Publish package to PyPI
        run: |
          poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }} 
